void mostrarMenu();
void mostrarResultadosCalculados ();
void mostrarDivnosepuede();
void mostrarFAcnosepuede();
void opcionNovalida ();
void FinPrograma ();
void CalculosREalizados ();
void ErroringreseNum ();
void realiceCalculos();
int pedirNumeroUno();
int pedirNumeroDos ();
int mostrarNumero1 (int z);
int mostrarNumero2 (int z);
int mostrarResultadoSuma (int z);
int mostrarResultadoResta (int z);
int mostrarResultadoMul (int z);
float mostrarResultadoDiv (float z);
int mostrarResFac1 (int z);
int mostrarResFac2 (int z);

